apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
  annotations:
    # use kubectl rollout history deploy order-service-deploy to see this annotation
    kubernetes.io/change-cause: "Deploying v3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: my-pod
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: vinsdocker/k8s-app:v3
        env:
        - name: DUMMY
          value: "8"
        ports:
        - name: "app-port"
          containerPort: 80