apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      team: team-a
  template:
    metadata:
      name: my-pod
      labels:
        team: team-a
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx