apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  # Possible values: Always, OnFailure, Never
  restartPolicy: Never
  containers:
  - name: ubuntu-container
    image: ubuntu
    # this is list of string 
    # can be form of : [ "date" ]
    args: 
      - "/bin/sh"
      - "-c"
      - "echo Hello Kubernetes! && sleep 20"

