apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  # Possible values: Always, OnFailure, Never
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
  - name: ubuntu-container
    image: ubuntu
    env:
    - name: "request.timeout"
      value: "10ms"
    - name: "spring.profiles.active"
      value: "dev"
    args:
      - "env"