apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
data:
  my-key: keyntot
  my-pass: pa$$
  another: another
---

apiVersion: v1
kind: Pod
metadata:
  name: podtot
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    envFrom:
    - configMapRef:
        name: sample-configmap
    args:
    - env